repos:
  - repo: local
    hooks:
    - id: jupyter-nb-clear-output
      name: jupyter-nb-clear-output
      files: ^notebooks/.*\.ipynb$
      stages: [commit]
      language: system
      entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    - id: black
      language_version: python3.9
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
    - id: pylint
      args: [--rcfile=.pylintrc]
      language_version: python3.9
